-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Grant permissions to application user
GRANT ALL PRIVILEGES ON DATABASE lp_platform TO lp_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lp_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO lp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO lp_app;
